# Generated by Django 4.1.2 on 2023-02-14 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_checkedoutbooks_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedoutbooks',
            name='reserved_books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.libraryinventory'),
        ),
    ]
